### ISSUE TITLE
Error: Cannot add a route without any connections

### ISSUE THREAD

**Issue by sebbel** [hoodiehq/hoodie-server-store#29]
heya :helicopter: 

While running the example from the README.md, the following error occurs:
Error: Cannot add a route without any connections

 throw new Error(msgs.join(' ') || 'Unknown error');
    ^
Error: Cannot add a route without any connections

Do I need to run any other applications while trying this out?
CouchDB is relaxing in the background :)

**Comment by gr2m** [comment]
ah good catch, I think the problem is the order of `server.connection` and `server.register`. Could you send a PR to fix it in README and in example.js?

**Comment by sebbel** [comment]
That didn't quite fix it :( now getting `Error: Unknown handler: proxy`

**Comment by gr2m** [comment]
So we can close this, right?
